[build]
  base = "."
  command = "npm run build"
  publish = "dist"

# Handle React Router client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
